DROP DATABASE IF EXISTS words;

CREATE DATABASE words;
USE words;

DROP TABLE IF EXISTS Words;
CREATE TABLE Words(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(50),
  definition VARCHAR(255),
  difficulty VARCHAR(50)
);

INSERT INTO Words(word, definition, difficulty)
VALUES
  ("adversary", "someone who offers opposition", "easy"),
  ("aplomb", "great coolness and composure under strain", "easy"),
  ("apprehensive", "in fear or dread of possible evil or harm", "easy"),
  ("aptitude", "inherent ability", "easy"),
  ("attentive", "taking heed", "easy"),
  ("banish", "send away from a place of residence, as for punishment", "easy"),
  ("barricade", "block off with barriers", "easy"),
  ("brackish", "slightly salty", "easy"),
  ("brandish", "move or swing back and forth", "easy"),
  ("circumference", "the size of something as given by the distance around it", "easy"),
  ("commotion", "confused movement", "easy"),
  ("concoction", "any foodstuff made by combining different ingredients", "easy"),
  ("conspicuous", "obvious to the eye or mind", "easy"),
  ("counter", "speak in response", "easy"),
  ("cunning", "shrewdness as demonstrated by being skilled in deception", "easy"),
  ("debris", "the remains of something that has been destroyed", "easy"),
  ("defiance", "a hostile challenge", "easy"),
  ("deft", "skillful in physical movements; especially of the hands", "easy"),
  ("destination", "the place designated as the end, as of a race or journey", "easy"),
  ("disdain", "lack of respect accompanied by a feeling of intense dislike", "easy"),
  ("dismal", "causing dejection", "easy"),
  ("dispel", "force to go away", "easy"),
  ("eavesdrop", "listen without the speaker's knowledge", "easy"),
  ("egregious", "conspicuously and outrageously bad or reprehensible", "easy"),
  ("engross", "consume all of one's attention or time", "easy"),
  ("exasperation", "a feeling of annoyance", "easy"),
  ("exhilarate", "fill with sublime emotion", "easy"),
  ("foresight", "seeing ahead; knowing in advance; foreseeing", "easy"),
  ("fragrance", "a distinctive odor that is pleasant", "easy"),
  ("furtive", "secret and sly or sordid", "easy"),
  ("grueling", "characterized by effort to the point of exhaustion", "easy"),
  ("gusto", "vigorous and enthusiastic enjoyment", "easy"),
  ("habitation", "the act of dwelling in or living permanently in a place", "easy"),
  ("hasten", "speed up the progress of; facilitate", "easy"),
  ("headway", "forward movement", "easy"),
  ("ignite", "cause to start burning", "easy"),
  ("illuminate", "make free from confusion or ambiguity", "easy"),
  ("impending", "close in time; about to occur", "easy"),
  ("imperious", "having or showing arrogant superiority", "easy"),
  ("jargon", "technical terminology characteristic of a particular subject", "easy"),
  ("jostle", "make one's way by pushing or shoving", "easy"),
  ("jut", "extend out or project in space", "easy"),
  ("kindle", "call forth, as an emotion, feeling, or response", "easy"),
  ("knoll", "a small natural hill", "easy"),
  ("luminous", "softly bright or radiant", "easy"),
  ("malleable", "easily influenced", "easy"),
  ("materialize", "come into being; become reality", "easy"),
  ("meander", "move or cause to move in a sinuous or circular course", "easy"),
  ("meticulous", "marked by extreme care in treatment of details", "easy"),
  ("monotonous", "sounded or spoken in a tone unvarying in pitch", "easy"),
  ("multitude", "a large indefinite number", "easy"),
  ("narrate", "give a detailed account of", "easy"),
  ("obscure", "not clearly understood or expressed", "easy"),
  ("ominous", "threatening or foreshadowing evil or tragic developments", "easy"),
  ("outlandish", "conspicuously or grossly unconventional or unusual", "easy"),
  ("persistent", "stubbornly unyielding", "easy"),
  ("pertinent", "having precise or logical relevance to the matter at hand", "easy"),
  ("plenteous", "affording an abundant supply", "easy"),
  ("potential", "existing in possibility", "easy"),
  ("pristine", "completely free from dirt or contamination", "easy"),
  ("recluse", "one who lives in solitude", "easy"),
  ("recuperate", "restore to good health or strength", "easy"),
  ("replenish", "fill something that had previously been emptied", "easy"),
  ("repugnant", "offensive to the mind", "easy"),
  ("restitution", "a sum of money paid in compensation for loss or injury", "easy"),
  ("sabotage", "destroy property or hinder normal operations", "easy"),
  ("scarcity", "a small and inadequate amount", "easy"),
  ("serenity", "the absence of mental stress or anxiety", "easy"),
  ("specimen", "an example regarded as typical of its class", "easy"),
  ("subside", "wear off or die down", "easy"),
  ("swarm", "move in large numbers", "easy"),
  ("tactic", "a plan for attaining a particular goal", "easy"),
  ("terse", "brief and to the point", "easy"),
  ("translucent", "allowing light to pass through diffusely", "easy"),
  ("uncanny", "surpassing the ordinary or normal", "easy"),
  ("unsightly", "unpleasant to look at", "easy"),
  ("versatile", "able to move freely in all directions", "easy"),
  ("vigilant", "carefully observant or attentive", "easy"),
  ("vulnerable", "capable of being wounded or hurt", "easy"),
  ("waft", "be driven or carried along, as by the air", "easy"),
  ("waver", "pause or hold back in uncertainty or unwillingness", "easy"),
  ("weather", "face and withstand with courage", "easy"),
  ("zeal", "a feeling of strong eagerness", "easy"),
  ("Abacinate", "blind by holding a red-hot metal plate before someone's eyes", "hard"),
  ("Abactinal", "located on the surface or end opposite to that on which the mouth is situated (of radiate animals)", "hard"),
  ("Acaulescent", "having no apparent stem above ground (of plants)", "hard"),
  ("Afflatus", "a strong creative impulse; divine inspiration", "hard"),
  ("Ataraxia", "peace of mind", "hard"),
  ("Arrant", "without qualification; used informally as intensifiers", "hard"),
  ("Brobdingnagian", "huge", "hard"),
  ("Bruit", "tell or spread rumors", "hard"),
  ("Brumous", "filled or abounding with fog or mist", "hard"),
  ("Burke", "get rid of, silence or suppress", "hard"),
  ("Cerulean", "deep blue like the color of a clear sky", "hard"),
  ("Chapfallen", "brought low in spirit", "hard"),
  ("Chasuble", "a long sleeveless vestment worn by a priest when celebrating Mass", "hard"),
  ("Claver", "talk socially without exchanging too much information", "hard"),
  ("Concordat", "a signed written agreement between two or more parties", "hard"),
  ("Cyprian", "resembling the ancient orgiastic worship of Aphrodite on Cyprus", "hard"),
  ("Dastard", "a despicable coward", "hard"),
  ("Decollate", "cut the head of", "hard"),
  ("Defalcate", "appropriate fraudulently to one's own use", "hard"),
  ("Devitrify", "become crystalline", "hard"),
  ("Devoir", "formal expression of respect", "hard"),
  ("Discalced", "barefoot or wearing only sandals", "hard"),
  ("Emulous", "characterized by or arising from imitation", "hard"),
  ("Embouchure", "the aperture of a wind instrument into which the player blows directly", "hard"),
  ("Epigone", "an inferior imitator or follower of someone", "hard"),
  ("Euphuism", "any artificially elegant style of language", "hard"),
  ("Exordium", "the introductory section of an oration or discourse", "hard"),
  ("Epistaxis", "bleeding from the nose", "hard"),
  ("Famulus", "a close attendant (as to a scholar)", "hard"),
  ("Fillip", "something that acts as a stimulus", "hard"),
  ("Flocculate", "form into an aggregated lumpy or fluffy mass", "hard"),
  ("Froward", "habitually disposed to disobedience and opposition", "hard"),
  ("Fulgurous", "amazingly impressive", "hard"),
  ("Fustian", "pompous or pretentious talk or writing", "hard"),
  ("Gallimaufry", "a motley assortment of things", "hard"),
  ("Gasconade", "an instance of boastful talk", "hard"),
  ("Gelid", "extremely cold", "hard"),
  ("Grampus", "predatory black-and-white toothed whale with large dorsal fin", "hard"),
  ("Ghat", "stairway in India leading down to a landing on the water", "hard"),
  ("Haecceity", "the essence that makes something the kind of thing it is", "hard"),
  ("Hebdomad", "any period of seven consecutive days", "hard"),
  ("Hiemal", "characteristic of or relating to winter", "hard"),
  ("Hobbledehoy", "an awkward bad-mannered adolescent boy", "hard"),
  ("Hoyden", "a girl who behaves in a boyish manner", "hard"),
  ("Hyaline", "resembling glass in transparency or translucency", "hard"),
  ("Hypostatize", "construe as a real existence, of a conceptual entity", "hard"),
  ("Icosahedron", "any polyhedron having twenty plane faces", "hard"),
  ("Imbrue", "permeate or impregnate", "hard"),
  ("Incalescence", "the property of being warming", "hard"),
  ("Incommensurable", "impossible to measure or compare in value or size or excellence", "hard"),
  ("Inculpate", "suggest that someone is guilty", "hard"),
  ("Involution", "the act of sharing in the activities of a group", "hard"),
  ("Jackanapes", "someone who is unimportant but cheeky and presumptuous", "hard"),
  ("Jactitation", "a false boast that can harm others", "hard"),
  ("Janissary", "a loyal supporter", "hard"),
  ("Khamsin", "an oppressively hot southerly wind from the Sahara that blows across Egypt in the spring", "hard"),
  ("Kiang", "wild ass of Tibet and Mongolia", "hard"),
  ("Kith", "your friends and acquaintances", "hard"),
  ("Knackered", "very tired", "hard"),
  ("Koine", "a common language used by speakers of different languages", "hard"),
  ("lagniappe", "a small gift given by a merchant to a customer", "hard"),
  ("lambent", "softly bright or radiant", "hard"),
  ("lancinating", "painful as if caused by a sharp instrument", "hard"),
  ("lenify", "cause to be more favorably inclined; gain the good will of", "hard"),
  ("leptorhine", "having a long narrow nose", "hard"),
  ("liege", "a feudal lord entitled to allegiance and service", "hard"),
  ("logomachy", "an argument about words or the meaning of words)", "hard"),
  ("lollop", "move or walk clumsily and with a bounce", "hard"),
  ("longanimity", "good-natured tolerance of delay or incompetence", "hard"),
  ("macaronic", "mixing two languages, especially Latin and another language", "hard"),
  ("mackle", "a printed impression that is blurred or doubled", "hard"),
  ("mahout", "the driver and keeper of an elephant", "hard"),
  ("majuscule", "one of the large alphabetic characters used as the first letter in writing or printing proper names and sometimes for emphasis", "hard"),
  ("malversate", "appropriate fraudulently to one's own use", "hard"),
  ("maunder", "wander aimlessly", "hard"),
  ("metonymy", "substituting the name of a feature for the name of the thing", "hard"),
  ("myrmidon", "a follower who carries out orders without question", "hard"),
  ("nacre", "the iridescent internal layer of a mollusk shell", "hard"),
  ("nevus", "a blemish on the skin that is formed before birth", "hard"),
  ("nitid", "bright with a steady but subdued shining", "hard"),
  ("nonesuch", "model of excellence or perfection of a kind", "hard"),
  ("nucha", "the back side of the neck", "hard"),
  ("objurgate", "censure severely", "hard"),
  ("obnubilate", "make less visible or unclear", "hard"),
  ("oneiric", "of or relating to or suggestive of dreams", "hard"),
  ("oppugn", "challenge the accuracy, probity, or propriety of", "hard"),
  ("oscitance", "an involuntary intake of breath through a wide open mouth", "hard"),
  ("palter", "be deliberately ambiguous or unclear in order to mislead", "hard"),
  ("pandiculation", "yawning and stretching (as when first waking up)", "hard"),
  ("pandurate", "having rounded ends and a contracted center", "hard"),
  ("parvenu", "a person who has suddenly risen to a higher economic status", "hard"),
  ("peculate", "appropriate fraudulently for one's own use", "hard"),
  ("peripety", "a sudden and unexpected change of fortune or reverse of circumstances (especially in a literary work)", "hard"),
  ("picaresque", "(of fiction) involving clever rogues or adventurers", "hard"),
  ("plenipotentiary", "a diplomat with full powers to take action or make decisions", "hard"),
  ("porphyria", "a genetic abnormality of metabolism causing abdominal pains and mental confusion", "hard"),
  ("pretermit", "disregard intentionally or let pass", "hard"),
  ("procurator", "a person authorized to act for another", "hard"),
  ("purlieu", "an outer adjacent area of any place", "hard"),
  ("quidnunc", "a person who meddles in the affairs of others", "hard"),
  ("quondam", "belonging to some prior time", "hard"),
  ("quietus", "euphemisms for death", "hard"),
  ("raillery", "light teasing", "hard"),
  ("rebarbative", "serving or tending to repel", "hard"),
  ("recusant", "someone who refuses to conform to established standards of conduct", "hard"),
  ("rescission", "the cancellation of a contract", "hard"),
  ("Rhadamanthus", "(Greek mythology) a judge of the dead in the underworld", "hard"),
  ("roister", "engage in boisterous, drunken merrymaking", "hard"),
  ("sacculated", "formed with or having saclike expansions", "hard"),
  ("saporous", "full of flavor", "hard"),
  ("sciolism", "pretentious superficiality of knowledge", "hard"),
  ("scupper", "drain that allows water on the deck of a vessel to flow overboard", "hard"),
  ("sempiternal", "having no known beginning and presumably no end", "hard"),
  ("secern", "mark as different", "hard"),
  ("slumgullion", "a thin stew of meat and vegetables", "hard"),
  ("subfusc", "devoid of brightness or appeal", "hard"),
  ("sumptuary", "regulating or controlling expenditure or personal behavior", "hard"),
  ("supernal", "of heaven or the spirit", "hard"),
  ("syllepsis", "use of a word to govern two or more words though agreeing in number or case etc. with only one", "hard"),
  ("synecdoche", "using part of something to refer to the whole thing", "hard"),
  ("taradiddle", "a trivial lie", "hard"),
  ("tatterdemalion", "a dirty shabbily clothed person", "hard"),
  ("temerarious", "presumptuously daring", "hard"),
  ("tincture", "a substance that colors metals", "hard"),
  ("tosh", "pretentious or silly talk or writing", "hard"),
  ("transude", "release (a liquid) in drops or small quantities", "hard"),
  ("trumpery", "ornamental objects of no great value", "hard"),
  ("ullage", "the amount that a container lacks of being full", "hard"),
  ("umbilicus", "a scar where the umbilical cord was attached", "hard"),
  ("urticate", "sting with or as with nettles and cause a stinging pain or sensation", "hard"),
  ("usufruct", "a legal right to use and profit from someone else's property", "hard"),
  ("valetudinarian", "weak or sickly person especially one morbidly concerned with his or her health", "hard"),
  ("vambrace", "cannon of plate armor protecting the forearm", "hard"),
  ("velleity", "desire in its weakest form", "hard"),
  ("vigesimal", "relating to or based on the number twenty", "hard"),
  ("vilipend", "belittle", "hard");
